### ISSUE TITLE
Feature request: Separate config for linting and autofixing

### ISSUE THREAD

**Issue by LendaVadym** [microsoft/vscode-typescript-tslint-plugin#101]
It's a feature request.
I want to auto fix a specific number of rules (not all).
It would be good if I can specify separate configuration files, e.g.:
tslint.json
tslint-autofix.json

first one would be used to lint files on the fly and hint the errors in IDE,
the second one would be used for auto fixing errors on save...

**Comment by mjbvz** [comment]
Can you please share more information about how this would be helpful for your workflow?

**Comment by LendaVadym** [comment]
> Can you please share more information about how this would be helpful for your workflow?


Hi,
I've separated tslint rules into two categories: 
 - can be autofixed (only rules that affect formatting);
 - all rules (including those can be autofixed);
This separation doesn't depend on "Has Fixer" label on particular rule.
Therefore, when I type some code in IDE, I want my code to be checked and highlighted by all rules (second category).
But when I press "Save" I want only formatting rules (first category) to be applied to my code and fix it in current file.

I don't want to move this logic into npm scripts because it needs to involve additional actions from developer while vscode-typescript-tslint-plugin extension is seamlessly integrated into VSCode.

At the moment if I configure VSCode with this setting:
   "editor.codeActionsOnSave": {
      "source.fixAll.tslint": true
   },

it will apply all rules from tslint.json that have fixers ("Has fixer" label)...
Therefore I wan't to separate first category into tslint-autofix.json and second category into tslint.json (will extend tslint-autofix.json) and provide both files to extension.

**Comment by mjbvz** [comment]
@LendaVadym Thanks. I think this workflow is out of scope of this extension.

You may want to investigate setting up a [vs code task](https://code.visualstudio.com/Docs/editor/tasks) that runs `tslint --fix` with your `tslint.autofix.json`. Then disable `source.fixAll`. That should let you get pretty close to the workflow you describe
