### ISSUE TITLE
Question about generic

### ISSUE THREAD

**Issue by TheBegining** [microsoft/vscode-typescript-tslint-plugin#102]
```
function Test<T>(fn: (a: T) => void, a: T): void;

function Test(fn: () => void): void;

function Test(fn: any, a?: any) {
  if(a!=null){
    fn(a);
  }else{
    fn();
  }
}

function fun() {}

const a = 1;

Test(fun,a);
```
The `fun` function is `()=>void`
but The tslint won't tell me `fun` is not assign to `(a:T)=>void`
![image](https://user-images.githubusercontent.com/17702287/60070344-dd6f2900-9748-11e9-9d0e-d3b21adcf28b.png)

**Comment by mjbvz** [comment]
This sounds like a regular TS question, not a tslint issue.

Please ask this on StackOverflow or file an issue against TypeScript
