### ISSUE TITLE
Tslint stops working in VSCode, not showing unhandled exceptions

### ISSUE THREAD

**Issue by jessesmall** [microsoft/vscode-typescript-tslint-plugin#103]
I was requested due to my review to create a new issue describing my problem and solution.
We were using tslint without any issues and then one day it stopped working. I was able to install the older deprecated version of tslint in visual studio code and that was able to actually give me some errors. The error was an un-handled exception due to having a list of mismatched projects in our angular.json and nx.json. By removing the un-necessary projects the old extension began to work correctly again, I then uninstalled the old version and re-installed the newer extension and all was working again. I noticed on the reviews a lot of people are reporting that the extension just stops working, I believe this is due to some un-handled exception being thrown like in my case but the new extension is not showing these errors for us like the old one was so there is no way of knowing how to fix it.

To reproduce this you just need to have an angular project that is using narwhal (nx), then under the nx.json add an extra project under the listed projects or remove a project from the angular.json this should throw an error with the old extension but will simply break the new extension.

The issue is not the extension breaking, but rather the extension not showing errors when it breaks like the old one was. We have fixed our own project and the extension is working great again, this is more for the information of other developers who may come across this issue, it would be great if we could see these errors instead of having to re-install the old deprecated one.

**Comment by erhise** [comment]
> To reproduce this you just need to have an angular project that is using narwhal (nx), then under the nx.json add an extra project under the listed projects or remove a project from the angular.json this should throw an error with the old extension but will simply break the new extension.
Could you specify what you mean by this?

I'm using nrwl/nx. I just realized that the tslint extension was not working as it should. Doing
* Uninstall tslint extension
* Install deprecated version
* Uninstall deprecated version
* Install tslint extension
made it work again but I did not modify the angular.json file. I am wondering what the unhandled exception might have been.

**Comment by jessesmall** [comment]
I think in your case you may have had a different error than me but sounds like the problem is the same, the errors are not being shown. Maybe the deprecated version had some sort of clean up that fixed whatever wasn't working correctly.

**Comment by ILlearnPrograming** [comment]
Only version 1.2.3 works for me. Newer versions don't work in VSCode.

**Comment by mbest** [comment]
It stops working for me as well, seemingly randomly. I have 1.3.3. I tried disable, restart, enable. Then the tslint errors show up, but the autofix feature still doesn't work. I had to exit VS Code and run it again, and now it's working.

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
