### ISSUE TITLE
Can't make it show errors in .html files

### ISSUE THREAD

**Issue by 0xR** [microsoft/vscode-typescript-tslint-plugin#104]
There are tslint plugins that run on .html files. Notable example are some checks from [angular codelyzer](https://github.com/mgechev/codelyzer). 

It would be nice if those error would show up inline in vscode when an .html file is opened.

I can't find any configuration option that can make it run on extensions other than .ts.

**Comment by mjbvz** [comment]
Unfortunately this is out of scope for this project as it is a typescript server plugin (which only handles JS/TS files)
