### ISSUE TITLE
Support for TypeScript custom rules without transpiling to JS

### ISSUE THREAD

**Issue by KrofDrakula** [microsoft/vscode-typescript-tslint-plugin#105]
Following up from [issue #131](https://github.com/Microsoft/vscode-tslint/issues/313) in the deprecated plugin repository, I'm wondering if this project would consider enabling dynamic loading of TypeScript custom rules.

Currently, enabling the `ts-node` loader in node allows rules authored in TypeScript to be loaded directly when invoking `tslint` via CLI, but I haven't been able to find a way to do this for the VSCode plugin without precompiling the custom rule first.

Given that the last comment mentions being able to enable `ts-node` within the language server, what would it take to enable such behaviour?

**Comment by mjbvz** [comment]
This is not possible because the plugin is run the TypeScript server. We have no control over the node environment the server runs the plugin in

To workaround this, you could try writing a JavaScript rule that invokes `ts-node` on your rule.ts file

**Comment by KrofDrakula** [comment]
OK, compiling the rules it is, then. Thank you!
