### ISSUE TITLE
Auto fix introduces new problems

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-typescript-tslint-plugin#108]
![image](https://user-images.githubusercontent.com/2193314/61748992-79934c80-ad56-11e9-86d8-9576fdd2aafb.png)

Auto fix

![image](https://user-images.githubusercontent.com/2193314/61749006-831cb480-ad56-11e9-92f7-c4956fc8654b.png)

Auto fix

![image](https://user-images.githubusercontent.com/2193314/61749019-8ca61c80-ad56-11e9-8275-26648bd0ae45.png)

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
