### ISSUE TITLE
1.2.0 - Cannot read tslint configuration - 'linterConfiguration.rules.delete is not a function'

### ISSUE THREAD

**Issue by FatalMerlin** [microsoft/vscode-typescript-tslint-plugin#109]
- tslint Version: 5.17.0
- typescript Version: 3.5.1

Steps to Reproduce:

1. Create new Microsoft SPFx 2016 onPrem solution (`yo @microsoft/sharepoint`)
2. Remove invalid extends configuration from `tslint.json` (Line 2)
3. Open `.ts`-file
4. Check VSCode Problems Output:

![image](https://user-images.githubusercontent.com/14237330/59756832-c8971f00-928a-11e9-9e03-5c49f9b23176.png)

**Comment by egamma** [comment]
Transferred the issue to the new typescript tslint plugin and reopened it.

**Comment by EugeneDyachenko** [comment]
For me helped to disable `eslint` vs code extension. Don't exactly know how it was connected

**Comment by mjbvz** [comment]
@FatalMerlin Were you using this extension or the deprecated one?

**Comment by FatalMerlin** [comment]
@mjbvz sorry for the late reply!

I was using this extension.

The problem was that the generated solution uses an outdated version of tslint, once I forced that to a current version with yarn everything worked as intended.

The extension didn't use the final tslint installation.

So, to everyone reading this, make sure that your projects tslint version is up-to-date. And sorry for keeping the solution to myself, I didn't realize that more people had the problem, I thought I was being stupid.

Shouldn't the extension use the global (or ideally the most up-to-date) version of tslint that is installed?

**Comment by mjbvz** [comment]
Thanks for the explanation.

We prefer the tslint version from the current workspace if it is available. I feel this is generally the expected behavior 

Let me know if you have any ideas on we could improve debugging errors like this

**Comment by FatalMerlin** [comment]
One possibility would be to include the path to the used tslint installation and is version.

But why do you prefer the workspace version? The extension is not tied to the open protect as, while I might be using it, another user might use a different editor without the plug-in or as in this case this might be based on a autogenerated template.

Can you maybe make the tslint version selectable? (Built-in, workspace, global?)

eslint and jshint are also looking for the packages globally as far as I know.
