### ISSUE TITLE
Auto fix [tslint] Exceeds maximum line length of 140 (max-line-length)

### ISSUE THREAD

**Issue by kresdjan** [microsoft/vscode-typescript-tslint-plugin#110]
I don't know if it is out of scope for this plugin. But having an auto fix for `[tslint] Exceeds maximum line length of 140 (max-line-length)` would be greatly appreciated.

**Comment by orta** [comment]
Yeah, that would need to be inside TSLint itself, not on this vscode plugin. My recommendation is to use something like [prettier](https://prettier.io).
