### ISSUE TITLE
Incorrect problem description.

### ISSUE THREAD

**Issue by scopchanov** [microsoft/vscode-typescript-tslint-plugin#111]
In my opinion the _should be_ part of

> The selector should be prefixed by "app" (https://angular.io/guide/styleguide#style-02-07) (component-selector)

is not correct. According to the provided [link](https://angular.io/guide/styleguide#style-02-07):

> Do use a prefix that identifies the feature area **or** the app itself.

The given example indeed shows `selector: 'hero'` as an inapropriate name, but `selector: 'toh-hero'` is totally acceptable, although it is not prefixed by `app` in this case.

**Comment by mjbvz** [comment]
I believe this is an issue with tslint itself or one of the rules, not with this plugin
