### ISSUE TITLE
Please add debounce time to showing errors

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-typescript-tslint-plugin#112]
tslint is unfriendly, showing squiggles for every error WHILE I'm typing.  This results in a poor user experience seeing squiggles all-day long when the squiggles will be resolves within a few seconds.

Please add an option, error debounce time so developers can set the delay between the broken lint rule being discovered and when the UI is updated with the said rule.  

I would set mine to 10 seconds and rarely see any errors while coding.

Thank you,

Karl

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
