### ISSUE TITLE
Deprecation Relating To TSLint Migration To ESLint

### ISSUE THREAD

**Issue by vindicatorr** [microsoft/vscode-typescript-tslint-plugin#115]
> Adds tslint to VS Code using...

Reference to: https://github.com/palantir/tslint/issues/4534
I actually JUST installed this extension and was about to test drive it for my first linting experience.
I followed through to the tslint repository from your link and found it was going to be deprecated.

So... is the plugin going the same way, and that everyone ought to transition to eslint as well?

**Comment by mjbvz** [comment]
That's your decision. Many existing projects use tslint and will not be able to/don't have a good reason to change over to eslint
