### ISSUE TITLE
Integration with Angular Codelyzer

### ISSUE THREAD

**Issue by ladislauNagy** [microsoft/vscode-typescript-tslint-plugin#116]
Hello, Integration with Angular Codelyzer is not very clear, strangely enough it works with the proper configuration.
I have the following settings in settings.json:
`"tslint.rulesDirectory": "./node_modules/codelyzer",
    "typescript.tsdk": "node_modules/typescript/lib"`
I this something supported in VSCode by default, or Codelyzer can integrate only with the TSLint extension?

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
