### ISSUE TITLE
Format on save not working at all (again)

### ISSUE THREAD

**Issue by jerrygreen** [microsoft/vscode-typescript-tslint-plugin#117]
This happened again - https://github.com/microsoft/vscode-typescript-tslint-plugin/issues/92

It's broken in `1.2.2` (works good in 1.2.1)

## VSCode Info

Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

## P.S.

I would like to disable version bumping in vscode, but every so often it's getting back to the latest (after a system reboot? I'm not sure)

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
