### ISSUE TITLE
TSLint throws an error on test directory.

### ISSUE THREAD

**Issue by Web-Engine** [microsoft/vscode-typescript-tslint-plugin#121]
I have encountered error `Cannot find module '~~~'` on my `test/` directory.

First, My directory structure below.
#### directory structure
```
- /
  - .vscode/
  - node_modules/
  - src/
    - libs/ (my util libraries)
    - errors/ (my custom exceptions)
    - models/ (sequelize models)
    - routes/ (route scripts)
    - index.ts (main script)

  - test/ (test directory with mocha)
  - typings/ (for type definition of mysql2 package)
  - package.json (also, package-lock.json)
  - tsconfig.json
  - tslint.json
```
and I use `paths` in tsconfig.
#### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es6",

    "module": "commonjs",
    "moduleResolution": "node",

    "strict": true,

    "baseUrl": "./",
    "paths": {
      "@libs/*": ["./src/libs/*"],
      "@errors/*": ["./src/errors/*"],
      "@models/*": ["./src/models/*"],
      "@test/*": ["./test/*"],
      "@/*": ["./src/*"],
    },
    "typeRoots": ["./typings", "./node_modules/@types"],
    "esModuleInterop": true,
    "noResolve": false,

    "plugins": [
      {
        "name": "typescript-tslint-plugin"
      }
    ]
  },
  "include": ["./src/*", "./typings/*", "./test/*"]
}
```

#### tslint.json
```json
{
  "extends": "tslint:recommended",
  "rulesDirectory": ["src/", "test/"],
  "rules": {
    "max-line-length": {
      "options": [120]
    },
    "new-parens": true,
    "no-arg": true,
    "no-bitwise": true,
    "no-conditional-assignment": true,
    "no-consecutive-blank-lines": false,
    "quotemark": [true, "single"],
    "no-console": {
      "severity": "warning",
      "options": ["debug", "info", "log", "time", "timeEnd", "trace"]
    }
  }
}
```

then, I trying to import the modules using `paths`.
#### src/index.ts
![image](https://user-images.githubusercontent.com/3965510/69109711-eb3c9680-0abb-11ea-8632-76922e2fc48b.png)

#### src/routes/api/1.0.0/users/index.ts
![image](https://user-images.githubusercontent.com/3965510/69109732-fa234900-0abb-11ea-92b0-8e0b59cf77e1.png)

#### test/reset.ts
![image](https://user-images.githubusercontent.com/3965510/69109638-b4ff1700-0abb-11ea-943b-3e46f34ccd52.png)

#### test/api/1.0.0/user/User.test.ts
![image](https://user-images.githubusercontent.com/3965510/69109659-c34d3300-0abb-11ea-89f1-e4fd8b0a2c66.png)

but, tslint throws the error on only `test/api/user.ts` file.
also, I found some weird situation.

#### Change src/ directory name to xxx/
I changed src directory name to xxx and all configs too.
but, same problem occurred in `xxx/` directory.

#### Move all test/**/*.test.ts file to test/*.test.ts
I moved all test file to test root directory.
then, in my test/*.test.ts file, tslint doesn't throw the error!!

Is tslint handle src directory specially?
or is my mistake?

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
