### ISSUE TITLE
"tslint.alwaysShowRuleFailuresAsWarnings": false should be the default

### ISSUE THREAD

**Issue by Masterxilo** [microsoft/vscode-typescript-tslint-plugin#122]
Currently, "tslint.alwaysShowRuleFailuresAsWarnings": true is configured by default globally.

It was confusing to me that in oder to make "no-shadowed-variable": {"severity": "error"} be recognized by vs I had to change this setting.

**Comment by Masterxilo** [comment]
without the **proper (should be default)** configuration "tslint.alwaysShowRuleFailuresAsWarnings": true
![image](https://user-images.githubusercontent.com/2378665/69174823-d8998000-0b02-11ea-8ae6-a64def1f2d70.png)
with the proper configuration in settings.json I can see that key will be shadowed and I am warned about this **error**
![image](https://user-images.githubusercontent.com/2378665/69174886-f961d580-0b02-11ea-9b66-7fee21b7f891.png)

It should not be necessary to configure this.
There are many places to treat all linting as warnings already.

**Vscode should not by default interpret the linting rules differently!**

**Comment by Masterxilo** [comment]
Here is real-world trouble caused by this: https://github.com/angular/angular-cli/issues/16231

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
