### ISSUE TITLE
Assing tslint.json to jsonc as comments are allowed

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-typescript-tslint-plugin#125]
With the fix for https://github.com/microsoft/vscode/issues/78821 you can now associate `tslint.json` with jsonc again.
This should be done in the extension.

jsonc now is only JSON +  comments.
To also allow trailing commas, this needs to be added to the schema.

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
