### ISSUE TITLE
Not working with tslint 6.0.0

### ISSUE THREAD

**Issue by submarines-and** [microsoft/vscode-typescript-tslint-plugin#128]
Updated tslint to latest version: 6.0.0. Plugin stopped working. Have tried reinstalling node modules, the plugin and vscode (using insiders build).

If I revert to 5.20.1 and restart vscode, it starts working again.

**Comment by snebjorn** [comment]
After updating to `prettier@2` and `tslint@6.1.0`

I'm getting these on every line

![image](https://user-images.githubusercontent.com/1266245/77571199-397bff00-6ecd-11ea-8362-c0015b3fcfa0.png)

**Comment by submarines-and** [comment]
Moved to eslint with typescript plugin (for which there is an extension that works fine).

    "eslint": "^7.1.0",
    "eslint-plugin-security": "^1.4.0",
    "@typescript-eslint/eslint-plugin": "^3.1.0",
    "@typescript-eslint/parser": "^3.1.0",

Closing this because I want to get rid of it from my open issues list :)
