### ISSUE TITLE
suppressWhileTypeErrorsPresent not working

### ISSUE THREAD

**Issue by canemacchina** [microsoft/vscode-typescript-tslint-plugin#130]
As pointed out by the documentation, I've tried to enable `suppressWhileTypeErrorsPresent` option into my `tsconfig.json` but it seem to not work. Instead, the same option from the vscode config file works fine.

Note that I've tried using both built-in version of TypeScript or workspace version, but the result still the same.

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
