### ISSUE TITLE
Support prettier v2

### ISSUE THREAD

**Issue by snebjorn** [microsoft/vscode-typescript-tslint-plugin#131]
After updating to prettier@2 I'm getting these on every line

![image](https://user-images.githubusercontent.com/1266245/77571199-397bff00-6ecd-11ea-8362-c0015b3fcfa0.png)

**Comment by mjbvz** [comment]
Closing as there is not enough information to investigate this

From the screenshot and description, this sounds more like a prettier issue than an issue with this extension

**Comment by snebjorn** [comment]
This was related to when prettier changed EOL from `auto` to `LF`

I'm unable to reproduce this now. However I think that error was correct as it was reporting that the EOL wasn't `LF` which prettier required.
The "real" issue was that vscode-prettier didn't change `CRLF` to `LF` when formatting https://github.com/prettier/prettier-vscode/issues/1327
