### ISSUE TITLE
Typescript Language service died

### ISSUE THREAD

**Issue by tackc** [microsoft/vscode-typescript-tslint-plugin#134]
Issue Type: <b>Bug</b>

I keep receiving an error that states: "The TypeScript language service died 5 times right after it got started. The service will not be restarted."

Extension version: 1.2.3
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.67GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Without logs, this could be a VS Code / TypeScript issues. Do you only see this when this extension is enabled?

**Comment by tackc** [comment]
The issue seems to be resolved as it has not occurred in a while
