### ISSUE TITLE
Support for typescript-eslint?

### ISSUE THREAD

**Issue by thibaut-d** [microsoft/vscode-typescript-tslint-plugin#135]
Hi,

[TSLint website](https://palantir.github.io/tslint/) now prints:

> :warning: TSLint has been deprecated as of 2019. Please see this issue for more details: Roadmap: [TSLint → ESLint](https://github.com/palantir/tslint/issues/4534). [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) is now your best option for linting TypeScript.

Does it mean that we should now rely on ESLint's VS Code extension or does this extension supports typescript-eslint?

Thanks

**Comment by mjbvz** [comment]
Yes we recommend migrating to use eslint and the eslint extension, which already has full support for typescript in eslint: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

A lot of existing project still use tslint so we'll continue maintaining this extension for the time being, but we don't plan to add significant new features to it
