### ISSUE TITLE
Missing autofix feature

### ISSUE THREAD

**Issue by Xesenix** [microsoft/vscode-typescript-tslint-plugin#136]
As  microsoft / vscode-tslint is beaing deprecated in favor of this plugin it misses some of deprecated plugin behaviors that are main reasons I am still using the deprecated plugin.

Will the new plugin handle autofix on save or should we be still using the deprecated plugin for it?

**Comment by Pitasi** [comment]
From readme: https://github.com/microsoft/vscode-typescript-tslint-plugin#auto-fix-and-auto-fix-on-save

**Comment by Xesenix** [comment]
Why should I run some action when it can be run automatically on save?

**Comment by Xesenix** [comment]
```
"editor.codeActionsOnSave": {
    "source.fixAll.tslint": true
}
```
