### ISSUE TITLE
Extension not working anymore: Not using the local TSLint version found

### ISSUE THREAD

**Issue by davidediak** [microsoft/vscode-typescript-tslint-plugin#137]
Hello,
for some reason, it stopped working today.
I get the following warning on each ts file:
```
Not using the local TSLint version found for 'project/file.ts'
To enable code execution from the current workspace you must enable workspace library execution
```
The project is not in a workspace (never has been). It's failing to work on all project.

**Comment by mjbvz** [comment]
The most recent update will prompt you if there is a workspace version of TSLint (and requires confirmation before loading that version). See https://github.com/microsoft/vscode-typescript-tslint-plugin#workspace-library-execution for details

If the feature is not working, please describe your workspace setup
