### ISSUE TITLE
"Always enable" library execution is reset

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-typescript-tslint-plugin#139]
Issue Type: <b>Bug</b>

I've been trying to pinpoint exactly when this happens, but twice today I've had to re-enable workspace execution for TSLint, despite choosing the "Always enable" option. 

I'm using the `TSLint: Manage Workspace Execution` command and selecting the third option to always enable.

<img width="618" alt="Screen Shot 2021-01-25 at 4 51 12 PM" src="https://user-images.githubusercontent.com/3672607/105784520-d19fa600-5f2d-11eb-8d30-6fdeb2c305a6.png">

Extension version: 1.3.3
VS Code version: Code - Insiders 1.53.0-insider (51d19635946a76d2f9007f9e4f4db1c26a0ebfae, 2021-01-25T20:19:58.295Z)
OS version: Darwin x64 19.6.0

**Comment by JounQin** [comment]
+1 for this, it is so noise...

**Comment by jonbeebe** [comment]
I have the same issue

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
