### ISSUE TITLE
Tslint is warning that a semicolon is missing with Angular NgModule decorator.

### ISSUE THREAD

**Issue by Caayu** [microsoft/vscode-typescript-tslint-plugin#140]
TSLint version: ~6.1.0
Angular version: ~11.2.5

![ngmodule](https://user-images.githubusercontent.com/46906076/111348489-0511cd80-865f-11eb-9ed4-6a08c4e9441f.png)

but some modules it doesn't

![image](https://user-images.githubusercontent.com/46906076/111348702-325e7b80-865f-11eb-8ff9-b30c9c042ee1.png)

**Comment by mjbvz** [comment]
This seems like a generic tslint issue. Does it happen when you run tslint on the command line?

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
