### ISSUE TITLE
TSlint broke auto import / ctrl + click 

### ISSUE THREAD

**Issue by hugoblanc** [microsoft/vscode-typescript-tslint-plugin#143]
TSlint suddenly stopped working correctly without making any changes on my side. 

The ctrl + click to navigate are loading indefinitely, same for autocompletion. 

I checked both vscode insider and vscode v1.56. The problem occure in both situation.

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
