### ISSUE TITLE
When using GitHub Pull Requests and Issues extension, TSServer and electron crash

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode-typescript-tslint-plugin#148]
Issue Type: <b>Bug</b>

Repro step:

1. See .ts file diff with GitHub Pull Requests extension
2. TSServer crashes

```
[Info  - 02:34:42.568] Using tsserver from: /Users/yk-yamada/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.6.20220211/node_modules/typescript/lib/tsserver.js
[Info  - 02:34:42.568] <syntax> Forking...
[Info  - 02:34:42.569] <syntax> Starting...
[Info  - 02:34:42.570] <semantic> Forking...
[Info  - 02:34:42.572] <semantic> Starting...
[Info  - 02:34:43.947] TSServer exited. Signal: SIGABRT
[Info  - 02:36:34.430] Starting TS Server 
[Info  - 02:36:34.430] Not starting server. Too many crashes.
```

<img width="372" alt="スクリーンショット 2022-02-14 11 35 14" src="https://user-images.githubusercontent.com/1955233/153791334-74785137-73ba-4f8c-9e19-135fb7f351cb.png">

Extension version: 1.3.3
VS Code version: Code - Insiders 1.65.0-insider (Universal) (bb221a61d29deabd99ee9431736d04f2175cb596, 2022-02-11T05:16:57.139Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (0.35GB free)|
|Process Argv|ui|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vsclayoutctrt:30405800
dsvsc009:30436273
pythonvsnew555cf:30426299
vsbas813:30436447
vscscmwlcmt:30428973
azactmsalcf:30432849

```

</details>

**Comment by mjbvz** [comment]
From https://github.com/microsoft/vscode/issues/143135, the last line of the log are: 

```
Info 3244 [12:28:07.440] [typescript-tslint-plugin] "Computing tslint semantic diagnostics for '^/review/Users/jkearl/Developer/vscode/src/vs/workbench/common/webview.ts'"
Info 3245 [12:28:07.440] [typescript-tslint-plugin] "(runTsLint) start"
Info 3246 [12:28:07.440] [typescript-tslint-plugin] "(loadLibrary) trying to load ^/review/Users/jkearl/Developer/vscode/src/vs/workbench/common/webview.ts"
Info 3247 [12:28:07.440] [typescript-tslint-plugin] "(getGlobalPackageManagerPath) Begin - Resolve Global Package Manager Path for: npm"
Info 3248 [12:28:07.852] [typescript-tslint-plugin] "'npm config get prefix' value is: /usr/local"
Info 3249 [12:28:07.852] [typescript-tslint-plugin] "(getGlobalPackageManagerPath) Done - Resolve Global Package Manager Path for: npm"
```

I suspect either the extension or tslint itself is treating the in-memory file as a on-disk file, and then not handling the resulting errors

**Comment by mjbvz** [comment]
Please test out the latest version of this extension. If it still doesn't fix the problem, I'll reopen but likely won't have time to investigate myself
