### ISSUE TITLE
Lint entire workspace or project.

### ISSUE THREAD

**Issue by dmitryshunkov** [Microsoft/vscode-typescript-tslint-plugin#20]
I have installed plugin locally in worspace following [these](https://github.com/Microsoft/typescript-tslint-plugin#with-vs-code) instructions. And tslint now shows errors only for opened files. Is it possible to configure plugin to show issues in Problems tab for all files in entire project? Is it possible to configure problem matcher as for old tslint plugin?

**Comment by dmitryshunkov** [comment]
So, in order to see all errors I added tasks.json file with next content:

````
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "lint",
            "problemMatcher": {
                "base": "$tslint5",
                "fileLocation": "absolute"
            }
        }
    ]
}
````

and installed [plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) itself.

**Comment by mjbvz** [comment]
Yes you need the VS Code extension to get the problem matcher, not just the plugin

**Comment by DanTup** [comment]
@mjbvz I have the new plugin installed but I'm only seeing issues for open files also. I already have the code above (from when I used the other plugin - which I've now removed).

I'm fairly sure that the lints used to just show up when I hit build (Cmd+Shift+B or run with F5) and the watcher was running, I never had to explicitly run a command before. Has this changed, or have I done something wrong?
