### ISSUE TITLE
Disable rule on next line quick fix

### ISSUE THREAD

**Issue by villelahdenvuo** [Microsoft/vscode-typescript-tslint-plugin#21]
The regular tslint plugin offers quick fixes to disable rules for specific lines, but it seems like this one doesn't.

**Comment by mjbvz** [comment]
Can you please provide an example? https://github.com/Microsoft/typescript-tslint-plugin/issues/22 maybe?

**Comment by mjbvz** [comment]
Closing as duplicate of Microsoft/typescript-tslint-plugin#22
