### ISSUE TITLE
Unclear README wording around usage and requirements

### ISSUE THREAD

**Issue by jmlane** [Microsoft/vscode-typescript-tslint-plugin#28]
As per the [README.md](https://github.com/Microsoft/vscode-typescript-tslint-plugin/blob/557d6a220f7750845412256e5660af14e53c28a3/README.md):

> ## Usage
> [...]
> This extension works out of the box with VS Code's built-in version of TypeScript. You do not need to configure the plugin in your tsconfig.json if you are using VS Code's version of TypeScript.
> [...]
> ## Differences with the vscode-TSLint extension
> [...]
> This extension requires that the tslint and typescript modules are installed either locally or globally. [...]

The quoted statements are confusing and seemingly contradictory: if the extension "works out of the box with VS Code's built-in version of TypeScript", why are the tslint and typescript modules required?

If the npm modules are required, that should probably be stated upfront, rather than left to the bottom of the readme.

If "works out of the box" means you don't need to specify the plugin config, that statement needs to be reworded to make this clear. The current wording reads as if you don't need to install anything additional (tslint, typescript) and can use a bundled version of TypeScript.

I will happily submit a PR with changes once the intended information is clarified for me.

**Comment by mjbvz** [comment]
Yes you need to install tslint either locally or globally
