### ISSUE TITLE
Panel shows automatically on startup on error

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-typescript-tslint-plugin#32]
The pattern of opening a panel on error is not encouraged by VSCode. I noticed this: https://github.com/Microsoft/vscode-tslint/blob/master/tslint/extension.ts#L176

I suggest to use a notification instead that is easier for the user to deal with. A panel is not easy to dismiss, takes a lot of vertical space and destroys my current workbench layout.

**Comment by mjbvz** [comment]
The plugin version of the extension does not open any panels itself. All output is through the TS extension which also does not automatically open any panels
