### ISSUE TITLE
Support json5 for tslint.json

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode-typescript-tslint-plugin#38]
Hello

I would like to request tslint.json be supported as json5 document. Often my whole config stops working because I left a trailing comma somewhere.

**Comment by glen-84** [comment]
Shouldn't this be reported against [TSLint](https://github.com/palantir/tslint)?

TSLint does support YAML configuration files, so you could use that.

**Comment by usernamehw** [comment]
https://github.com/palantir/tslint/issues/1721

**Comment by mjbvz** [comment]
Closing as an upstream tslint issue
