### ISSUE TITLE
Change default of "tslint.jsEnable" to true (?)

### ISSUE THREAD

**Issue by glen-84** [microsoft/vscode-typescript-tslint-plugin#39]
Or, better yet, base it on the presence of `jsRules` in `tslint.json`.

It's somewhat surprising that if you:

* Set `allowJs` to `true` in `tsconfig.json`, and
* Set `jsRules` to `true` (or to a non-empty object) in `tslint.json`

... there is still no linting in JS files.

**Comment by SharakPL** [comment]
What is `"tslint.jsEnable": true` suppose to do anyway? I have typescript and tslint installed globally (tslint@5.12.0, typescript@3.2.2) and have this extension installed in my vscode. I expected for typescript linting to work without the need for `// @ts-check` in my js files, but it doesn't.

**Comment by glen-84** [comment]
@SharakPL,

1. Remove `jsRules` if you don't want `tslint` to lint JavaScript files.
2. Set `checkJs` to `true` in `tsconfig.json` if you want TypeScript to [check all JavaScript files](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files).

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
