### ISSUE TITLE
Support alwaysShowRuleFailuresAsWarnings option

### ISSUE THREAD

**Issue by cyrilletuzi** [Microsoft/vscode-typescript-tslint-plugin#4]
Thanks for this extension.

Is it possible to have the same `alwaysShowRuleFailuresAsWarnings` option as in the classic TSLint extension?

I'm teaching programming courses, and lint errors shown as syntax errors is really disturbing for new developers.

**Comment by cyrilletuzi** [comment]
(I would even argue it should be the default, but this is subject to debate).

**Comment by mjbvz** [comment]
You can configure this in your jsconfig/tsconfig: https://github.com/Microsoft/typescript-tslint-plugin#configuration-options

Will open a new issue to track using vs code settings for these config options

**Comment by csvn** [comment]
Are you using workspace version inside VSCode? When using built-in VSCode typescript version, the settings in `tsconfig.json` are not applied. There is a section about this on the README.md.

>This extension works out of the box with VS Code's built-in version of TypeScript. You do not need to configure the plugin in your tsconfig.json if you are using VS Code's version of TypeScript.
>
> If you are using a workspace version of typescript, you must currently configure the TS Server plugin manually by following these instructions

**Comment by Davilink** [comment]
I tried both.
