### ISSUE TITLE
Get the list of files to lint from the TS project

### ISSUE THREAD

**Issue by glen-84** [microsoft/vscode-typescript-tslint-plugin#40]
If I run `tslint -p .`, it only lints files included in the TS project.

This extension is linting files outside of the project (as specified in the `tsconfig.json` file).

I don't yet use the `linterOptions.exclude` setting in `tslint.json/yaml`, but that should probably also be respected.

**Comment by chongruei** [comment]
Has any solution for this?

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
