### ISSUE TITLE
Feature Request: Select tslint config by file name

### ISSUE THREAD

**Issue by tommck** [Microsoft/vscode-typescript-tslint-plugin#42]
So, in my applications, I typically have a tslint.json and a tslint.spec.json.
We use the spec linting rules for unit tests and the other for everything else

Can we please have a way to configure this?

**Comment by mjbvz** [comment]
Check out the `tslint.configFile` [setting](https://github.com/Microsoft/vscode-typescript-tslint-plugin#configuration)

**Comment by tommck** [comment]
That allows you to set one config file. I want to use a different one based
on the file name.

I don't see how this will help me

**Comment by mjbvz** [comment]
Then have you tried just creating separate `tsconfig.json` files: one under tests and one at the root for the rest?

**Comment by tommck** [comment]
Our tests live right next to the code.
It's a very common pattern

Foo.ts
Foo.spec.ts

**Comment by villelahdenvuo** [comment]
This is a very common use case I would say.

**Comment by mbest** [comment]
@mjbvz I'm running into this issue also. In our case, we have config for all files and another just for non-spec files. But with the extension, we can only see the linting error from the main config.

**Comment by mjbvz** [comment]
This extension (and TSLint itself) have been deprecated for multiple years now so this feature request will almost certainly never be implemented. I suggest migrating to eslint
