### ISSUE TITLE
`ordered-imports` causes imports to freak out upon formatting.

### ISSUE THREAD

**Issue by TheGrimSilence** [Microsoft/vscode-typescript-tslint-plugin#46]
When you have imports that are out of order, you get this warning:
![screenshot_11](https://user-images.githubusercontent.com/11479772/51655258-d65da800-1f69-11e9-80f5-cd26ce6a0384.png)
But if you format the document, your imports become scrambled like this:
![screenshot_12](https://user-images.githubusercontent.com/11479772/51655272-f1c8b300-1f69-11e9-9d78-76a13bb006de.png)
This stems from TSLint trying to `auto-fix` this issue, but for some reason it can't seem to get it right.

I know this extension is expiremental, I'm not complaining at all. Just a simple heads up. 
<kbd>Shift</kbd>+<kbd>CTRL</kbd>+<kbd>O</kbd> easily fixes this, *as long as you run it before formatting*.

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this
