### ISSUE TITLE
is it support with git diff lines or only works on the changed lines

### ISSUE THREAD

**Issue by hello-chenchen** [Microsoft/vscode-typescript-tslint-plugin#48]
Hi, for our team, there are many tslint errors highlight on a typescript file.
but these errors highlight was written by other team. we don't want to change other team's source code.
So, i want to know is it support with git diff lines or the changed lines?
If, not support, can you log a new feature for this requirement.
Thanks~

**Comment by mjbvz** [comment]
This is not supported and is out of scope of this extension. You could write a [custom task](https://code.visualstudio.com/Docs/editor/tasks) that would run tslint and only return errors from changed lines
