### ISSUE TITLE
Error messages appear multiple times

### ISSUE THREAD

**Issue by Gelio** [microsoft/vscode-typescript-tslint-plugin#49]
I played around with this plugin and I found a bug. Error messages were duplicated multiple times for one failure.

![image](https://user-images.githubusercontent.com/889383/51801091-8288e280-2239-11e9-8440-a98f6881b275.png)

![image](https://user-images.githubusercontent.com/889383/51801095-8ae11d80-2239-11e9-93a3-37a54d387245.png)

It does not go away after restarting the workspace or restarting the TS server.

The problem does not occur when using the regular TSLint extension.

Extension version: 0.4.0
Typescript version: 3.2.4
Typescript tslint plugin version: 0.3.0
Tslint version: 5.12.1

**Comment by mjbvz** [comment]
Can you please share that example code as text

**Comment by Gelio** [comment]
I deleted that project. I can still extract the code from the screenshot. Here you go:

```ts
const array = [
  1,
  2,
  4,
  5,
  6,
  { object: true },
  ['nested array', { another: { one: 1 } }]
];
```

I do not think this is a problem with just this exact piece of code. I had the same issue with error messages appearing multiple times with other rule violations.

**Comment by mikfoo** [comment]
We've had this happen multiple times as well. Haven't figured out how to reproduce it yet unfortunately.

**Comment by adamdry** [comment]
Yeah I get this a lot in our project:
![image](https://user-images.githubusercontent.com/7360709/57063361-e1d41400-6cba-11e9-8f94-34700c1c40f3.png)

**Comment by mjbvz** [comment]
I'm not able to repro this. @Gelio were you on windows? And are you still seeing this with the latest version of this extension (and of the plugin)?

**Comment by Gelio** [comment]
Yes, that was on Windows. I have not used this extension recently, so I cannot tell with certainty that the problem no longer occurs. I have created a playground for testing this extension:
https://github.com/Gelio/vscode-typescript-tslint-plugin-playground

and after a few minutes of testing, the problem no longer occurs and error messages are listed only once.

I will try to work on a typescript project for longer with this extension enabled and let you know how it goes 🙂 I suggest keeping this issue open for now

**Comment by adamdry** [comment]
@mjbvz I will try and create an example project from my current project which shows the issue and share it. I should have it done by middle of next week.

**Comment by michaelkolber** [comment]
This is still occurring for me on Windows in all projects. Each error appears 7 times.

**Comment by ale8k** [comment]
Still happening on windows, some 4 times, some 9 times, it's inconsistent as to what's causing it. Restarting VSC seems to solve it for a couple mins though.

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
