### ISSUE TITLE
clarify when tsconfig plugins configuration is necessary

### ISSUE THREAD

**Issue by jrr** [Microsoft/vscode-typescript-tslint-plugin#50]
From the readme:

> If you are using VS Code 1.30 or older and are using a workspace version of typescript, you must currently configure the TS Server plugin manually by following these instructions

I'm on VS Code 1.30.2 and a workspace version typescript, and it seems that it's not necessary to add any extra configuration to tsconfig.json. (rules in my tslint.json cause squiggles in VS Code)

Is the readme wrong? Perhaps the extra configuration became unnecessary at some 1.30.x patch level?

**Comment by mjbvz** [comment]
What are you trying to configure?

**Comment by mjbvz** [comment]
ok, since everything seems to be working and since this documentation will be irrelevant once VS Code 1.31 stable ships, I'm closing this
