### ISSUE TITLE
Change color coding of "defaultSeverity" property

### ISSUE THREAD

**Issue by AndreasNasman** [Microsoft/vscode-typescript-tslint-plugin#53]
Hi!

I like to set `defaultSeverity` to `error` in my _tslint.json_, and it would be helpful if the issues where colored with the correct color, i.e. red in this example.

<img width="440" alt="skarmavbild 2019-02-10 kl 20 42 56" src="https://user-images.githubusercontent.com/17124245/52538100-2b295d00-2d77-11e9-9158-a505ae5def64.png">

<img width="468" alt="skarmavbild 2019-02-10 kl 20 44 13" src="https://user-images.githubusercontent.com/17124245/52538102-311f3e00-2d77-11e9-834c-05c4aa44e425.png">

**Comment by mjbvz** [comment]
In VS Code, try also setting `"tslint.alwaysShowRuleFailuresAsWarnings": "false"`

**Comment by AndreasNasman** [comment]
@mjbvz Thanks, didn't know of this setting!
