### ISSUE TITLE
Missing "Fix all auto-fisable tslint failures" from Command Pallete

### ISSUE THREAD

**Issue by ackvf** [Microsoft/vscode-typescript-tslint-plugin#57]
Despite the option being available and working from the _Quick Fix..._ menu,
![image](https://user-images.githubusercontent.com/2313018/52853404-c88be480-311b-11e9-90ba-03f832b7dd06.png)

it is not accessible from the _Command Pallete..._.
![image](https://user-images.githubusercontent.com/2313018/52853403-c45fc700-311b-11e9-85bd-e76783ac0168.png)

**Comment by ackvf** [comment]
I would like to be able to invoke command `Fix all auto-fixable tslint failures` from pallete similarly to how ESLint allows that, rather than having to target a problem in an editor and invoke the quick fix popup.

**Comment by gluons** [comment]
[Old TSLint extension](https://marketplace.visualstudio.com/items?itemName=eg2.tslint) have this command. But this new extension don't have this command.

Please bring it back.
