### ISSUE TITLE
autoFixOnSave does not work

### ISSUE THREAD

**Issue by weagle08** [Microsoft/vscode-typescript-tslint-plugin#59]
Moved from the TSLint extension marked deprecated to this extension and the autoFixOnSave is not supported or does not work. If it is supported how do I enable it?

**Comment by mjbvz** [comment]
See instructions and documentation here: https://github.com/Microsoft/vscode-typescript-tslint-plugin#auto-fix-and-auto-fix-on-save

**Comment by weagle08** [comment]
Thanks! I looked at 3 different posts about the fix on save and this link was not given in any of the responses that I saw.
