### ISSUE TITLE
How can one execute fix all?

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-typescript-tslint-plugin#6]
Using tslint extension I have this as a keybinding:
```json
{
  "key": "ctrl+shift+alt+z",
  "command": "tslint.fixAllProblems",
  "when": "resourceExtname == '.ts'"
}
```
Or from command palette: `TSLint: Fix all auto-fixable problems`.

Is it possible to have the same functionality from this plugin?

---

I know this way:
1. click on warning
1. open quick fix menu
1. find that item in the menu `Fix all auto-fixable tslint failures`

^ That's too long

---

Not a fan of fixing on save either.

**Comment by mjbvz** [comment]
This requires https://github.com/Microsoft/vscode/issues/62110 or similar upstream
