### ISSUE TITLE
Some workspace and user settings are ignored

### ISSUE THREAD

**Issue by tjahn** [microsoft/vscode-typescript-tslint-plugin#62]
Hello,

I was trying to set "tslint.ignoreDefinitionFiles" to false.
However, unmarking the checkbox in the User-Settings or Workspace-Settings of Visual Studio 3.31.1 has no effect. Unmarking the checkbox results in the setting to be undefined, instead of being set to false explicitly. Inserting the settings in json-mode is working.

Also, the check-box is unchecked by default, but the plugin manual says, that its default is true. 
It's probably necessary to tell VSCode about this default value or something to fix that.

Many thanks for the plugin

**Comment by mjbvz** [comment]
What we want a three state value for these settings: `true`, `false`, and `unset`, with unset falling back to use the configuration from the `tsconfig.json`

With the current design of the settings UI, we cannot tell `false` from `unset`. Not sure what the best way to fix this is

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
