### ISSUE TITLE
Typescript language server doesn't discover tslint installed globally with Yarn

### ISSUE THREAD

**Issue by Jwpe** [microsoft/vscode-typescript-tslint-plugin#65]
Hi there,

Since switching to the new plugin (v1.0), the configuration option to tell `typescript-tslint-plugin` which package manager I'm using (`tslint.packageManager` in my VS Code settings) seems to have disappeared - Code now reports it as an unrecognised configuration option. 

The only way I was able to resolve the issue was to go into the source code of `typescript-tslint-plugin` in the `node-modules` of `vscode-typescript-tslint-plugin` and hard-code `yarn` as the package manager within [`runner/index.ts`](https://github.com/Microsoft/typescript-tslint-plugin/blob/master/src/runner/index.ts). 

I hope that I'm missing something and that there's an easier way to sort this out - is there a new way to supply this configuration property? 

Thanks!

**Comment by ExE-Boss** [comment]
The same occurs when it’s installed with `pnpm`.
