### ISSUE TITLE
How does this relate to the existing tslint plugin from egamma?

### ISSUE THREAD

**Issue by chillitom** [Microsoft/vscode-typescript-tslint-plugin#7]
Just curious if this is a replacement for or in addition to the existing popular VS Code [tslint ](https://marketplace.visualstudio.com/items?itemName=eg2.tslint) plugin from @egamma?

**Comment by csvn** [comment]
It's meant to be a replacement. By making the linting run as a [Typescript plugin](https://github.com/Microsoft/typescript-tslint-plugin), it avoids the issue where TSLint runs an extra Typescript program instance in the same workspace, as well as being able to use certain rules that require type info.

There is a gap in the functionality of this plugin compared to `vscode-tslint`, that was being tracked in [this issue on the original fork of the TS plugin](https://github.com/angelozerr/tslint-language-service/issues/32).

The Typescript tslint plugin is being actively worked on, and the repo was published just some days ago, so there might still be some rough edges. Considering the speed that the VSCode team has in building features, I would not be suprised if this was plugin was the most popular and used one in the near future.

**Comment by egamma** [comment]
@csvn is correct the goal is to gradually migrate from vscode-tslint to this new extension that uses the typescript plugin. This is a rough roadmap https://github.com/Microsoft/typescript-tslint-plugin/issues/1
