### ISSUE TITLE
False positive on missing whitespace for React .tsx files

### ISSUE THREAD

**Issue by PhishyFish** [microsoft/vscode-typescript-tslint-plugin#70]
**Expected Behavior**
No errors raised by tslint.

**Actual Behavior**
I'm receiving `missing whitespace (whitespace)` errors for all opening brackets (`<`).
<img width="720" alt="tslint-whitespace-error" src="https://user-images.githubusercontent.com/9098023/54249840-e3752d00-44fe-11e9-9864-cbdd226fee17.png">

**Misc**
- I'm using [`tslint-config-airbnb`](https://www.npmjs.com/package/tslint-config-airbnb) for rules.
- Package versions (project and global): `tslint@5.13.1`, `typescript@3.3.3333`

**Comment by pravesh-curefit** [comment]
Facing the same issue in ts files.

<img width="545" alt="Screenshot 2019-03-19 at 11 13 53 PM" src="https://user-images.githubusercontent.com/33955423/54629095-de832100-4a9c-11e9-991e-79fdc5109a09.png">

Using custom tslint rules.
tslint version 5.11.0

**Comment by mjbvz** [comment]
Please share the text of the code when positing with screenshots, along with the source of your tslint file (preferably as a small example project git repo)

**Comment by mjbvz** [comment]
Closing as we need easy steps to reproduce this
