### ISSUE TITLE
'no-unused-variable' issues are not being linted

### ISSUE THREAD

**Issue by evenfrost** [Microsoft/vscode-typescript-tslint-plugin#71]
In short: what is the status of implementing the linting of this rule in current VS Code TSLint plugin? Old version [couldn't handle it](https://github.com/Microsoft/vscode-tslint/issues/185), what about this one?  

I know there's been plenty of discussion about TypeScript's `noUnusedLocals` vs TSLint's `no-unused-variable`, and latter being [deprecated](https://github.com/palantir/tslint/issues/4046) first but now due to user response it's considered to be [undeprecated](https://github.com/palantir/tslint/issues/4100). The main argument in favour of leaving `no-unused-variable` as it is that it helps in development process not throwing errors on compiling (as `noUnusedLocals` does) but being worked out later as you commit (using pre-commit linting e.g. with `husky` and `lint-staged`).

**Comment by mjbvz** [comment]
No plans to do extra work to support this
