### ISSUE TITLE
Feedback from the marketplace

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-typescript-tslint-plugin#72]
![image](https://user-images.githubusercontent.com/4674940/54834108-b520eb80-4c7c-11e9-8ad1-97c0319fc44f.png)

**Comment by glen-84** [comment]
The user updated his review ...

```
After another hour of trying I finally got the extension to work.
The installation process is really unclear and error-prone.
But now everything is working.
======================================

...
```

**Comment by atishpatel** [comment]
![Screenshot from 2019-05-16 18-00-07](https://user-images.githubusercontent.com/6618430/57892423-7b93d900-7804-11e9-8cba-7229d914243b.png)

Editing my tslint.json files didn't work and i couldn't figure out why. Spent an hour trying to figure out why and was about to start an issue here.

Eventually, i saw a tiny caution sign on the bottom right where it said "Typescript" - by the smiley face. When i clicked on it said `tslint` needed to be in the workspace and to install it using `npm install tslint`. Once i installed it to the local space things started to work again.

**Comment by glen-84** [comment]
@atishpatel You can also use a global installation of tslint.

**Comment by atishpatel** [comment]
Thanks glen. I read that too once i noticed the tiny caution icon by the world TypeScript in vscode. The main issue is that the extension doesn't indicate that needs to be done other than that tiny caution sign. I think that's why many people think this package is broken. :man_shrugging:

**Comment by mjbvz** [comment]
@atishpatel Adding note to the readme is a good idea. But we don't actually generate any sort of caution sign so I'm not sure where that's coming from. Do you still have the old tslint plugin installed?
