### ISSUE TITLE
fixAll is not available in source action.

### ISSUE THREAD

**Issue by RamyRais** [Microsoft/vscode-typescript-tslint-plugin#75]
the fixAll, is not available in Source action. I would like to have it for the keybinding.

Vscode version: 1.32.3 
OS: macOS Mojave 10.14.4

<img width="470" alt="Screenshot 2019-04-01 at 13 20 38" src="https://user-images.githubusercontent.com/4824541/55323980-0309d080-5481-11e9-8f8b-4a4bc6757e7a.png">

**Comment by mjbvz** [comment]
If a file does not have tslint errors, `fix all` will not show up in the source menu. This does not effect configuring keybinding

**Comment by RamyRais** [comment]
should it show when i have warning? because i have warning, but still does not show.

**Comment by ShadabFaiz** [comment]
Here you can see there is warning for unUserLocalVariable
![Raw WArning](https://user-images.githubusercontent.com/8160121/63919099-af190d00-ca5b-11e9-94a0-096b15c53fec.png)

**Comment by RenaudF** [comment]
I was having the same issue, it seems going from
`"tslint.alwaysShowRuleFailuresAsWarnings": true,` to
`"tslint.alwaysShowRuleFailuresAsWarnings": false,`
made it work again... Perhaps tslint doesn't pick up on them when they're shown as warnings?
