### ISSUE TITLE
Looks like the extension locks some files.  Impossible to delete the node_modules folder.

### ISSUE THREAD

**Issue by kevinbeaudoin** [microsoft/vscode-typescript-tslint-plugin#79]
We've recently moved from the old TSLint extion to the official one since the one we were using is now deprecated.  Since we've moved to the new one, we're facing issue were we cannot delete our node_modules folder when the extension is active.  Deleting the folder takes a lot of time and returns an error indicating that files in the @types folder can't be deleted.  If we disable the extension and reload vscode we can then delete without any issue.

**Comment by mjbvz** [comment]
This sounds like https://github.com/Microsoft/TypeScript/issues/29407

Are you sure you only hit this when using this extension?

**Comment by mjbvz** [comment]
Closing as upstream issue
