### ISSUE TITLE
What errors does source.fixAll.tslint fix on save?

### ISSUE THREAD

**Issue by ideoclickVanessa** [Microsoft/vscode-typescript-tslint-plugin#82]
Is there a list of errors that source.fixAll.tslint will automatically fix on save?

I like the idea of auto-fixing the import alphabetization errors on save; however, may or may not want unused vars or console.log()s to be removed upon save while I'm still working with not yet completed code.

**Comment by mjbvz** [comment]
Any rules that  marked as `has-fixer` in the tslint rule list should be autofixable: https://palantir.github.io/tslint/rules/
