### ISSUE TITLE
Bug with a spread operator

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/vscode-typescript-tslint-plugin#85]
If you do the following:

```bash
git clone git@github.com:restify-ts/router.git
cd router
git checkout 11a929
yarn
npx tslint -p .
```

you can see the tslint errors:

```text
ERROR: ./router/src/router.ts:52:20 - non-arrow functions are forbidden
ERROR: ./router/src/router.ts:53:15 - Shadowed name: 'handle'
ERROR: ./router/src/router.ts:59:20 - Identifier 'key' is never reassigned; use 'const' instead of 'let'.
```

then open `src/router.ts` in VS Code and you can see that the `vscode-typescript-tslint-plugin` not work.

I think the bug is related to the spread operator. If we comment out [37 line][1], the plugin works as expected:

```ts
  all(...arg) {
    httpMethods.forEach(method => {
      // this.on(method, ...arg);
    });
    return this;
  }
```

[1]: https://github.com/restify-ts/router/blob/11a92932a1bb19a37b34525d1b3414d62078ed48/src/router.ts#L37

**Comment by mjbvz** [comment]
Seems to be working for me:

![Screen Shot 2019-05-01 at 10 45 11 AM](https://user-images.githubusercontent.com/12821956/57032057-40878800-6bfe-11e9-8fd9-6f7b110ff351.png)

What VS Code version and OS are you on?

**Comment by KostyaTretyak** [comment]
VS Code 1.33.1, Ubuntu 16.04 (OS: Linux x64 4.15.0-48-generic)

**Comment by KostyaTretyak** [comment]
Maybe you did not do `git checkout 11a929` before?

**Comment by mjbvz** [comment]
I'm on that commit. Are the implicitAny errors and other non-tslint errors expected?

**Comment by mjbvz** [comment]
You can also check the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

Look through that log file for lines that mention tslint, such as `Info 224  [10:46:52.902] [typescript-tslint-plugin] "Computing tslint semantic diagnostics for '/Users/matb/projects/san/router/src/node.ts'"`

If you can share the log, I can see if it shows something odd going on

**Comment by KostyaTretyak** [comment]
My log file: [tsserver.log](https://github.com/Microsoft/vscode-typescript-tslint-plugin/files/3135523/tsserver.log)

**Comment by mjbvz** [comment]
It looks like something going wrong with your copy of typescript, see the line:

```
Err 104   [21:11:10.146] Exception on executing command delayed processing of request 17:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at Object.first (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:1097:15)
        at getArgumentArityError (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:50167:32)
        at resolveCall (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:50307:41)
        at resolveCallExpression (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:50593:20)
        at resolveSignature
...
```

If you disable this extension, do you get any errors in this project?

Also, can you please test this using `typescript@next` by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions) https://github.com/Microsoft/TypeScript/issues/30591 suggest this debug failure should be fixed in `@next`

**Comment by KostyaTretyak** [comment]
With `typescript@3.4.5` the problem has disappeared. @mjbvz, thanks for the help!
