### ISSUE TITLE
Failed to load module 'typescript-tslint-plugin'

### ISSUE THREAD

**Issue by pikadun** [Microsoft/vscode-typescript-tslint-plugin#86]
日志显示找不到'typescript-tslint-plugin'模块，下面的这些路径里确实没有这些模块。
使用node全局安装'typescript-tslint-plugin'，会存放在"C:\Users\xxx\AppData\Roaming\npm"目录下

`
Failed to load module 'typescript-tslint-plugin': Error: Could not resolve JS module 'typescript-tslint-plugin' starting at 'c:/Program Files/Microsoft VS Code/resources/app/extensions/node_modules/node_modules'. Looked in: c:/Program Files/Microsoft VS Code/resources/app/extensions/node_modules/typescript-tslint-plugin/package.json, c:/Program Files/Microsoft VS Code/resources/app/extensions/node_modules/typescript-tslint-plugin.js, c:/Program Files/Microsoft VS Code/resources/app/extensions/node_modules/typescript-tslint-plugin.jsx, c:/Program Files/Microsoft VS Code/resources/app/extensions/node_modules/typescript-tslint-plugin/index.js, c:/Program Files/Microsoft VS Code/resources/app/extensions/node_modules/typescript-tslint-plugin/index.jsx, c:/Program Files/Microsoft VS Code/resources/app/node_modules/typescript-tslint-plugin/package.json, c:/Program Files/Microsoft VS Code/resources/app/node_modules/typescript-tslint-plugin.js, c:/Program Files/Microsoft VS Code/resources/app/node_modules/typescript-tslint-plugin.jsx, c:/Program Files/Microsoft VS Code/resources/app/node_modules/typescript-tslint-plugin/index.js, c:/Program Files/Microsoft VS Code/resources/app/node_modules/typescript-tslint-plugin/index.jsx, c:/Program Files/Microsoft VS Code/resources/node_modules/typescript-tslint-plugin/package.json, c:/Program Files/Microsoft VS Code/resources/node_modules/typescript-tslint-plugin.js, c:/Program Files/Microsoft VS Code/resources/node_modules/typescript-tslint-plugin.jsx, c:/Program Files/Microsoft VS Code/resources/node_modules/typescript-tslint-plugin/index.js, c:/Program Files/Microsoft VS Code/resources/node_modules/typescript-tslint-plugin/index.jsx, c:/Program Files/Microsoft VS Code/node_modules/typescript-tslint-plugin/package.json, c:/Program Files/Microsoft VS Code/node_modules/typescript-tslint-plugin.js, c:/Program Files/Microsoft VS Code/node_modules/typescript-tslint-plugin.jsx, c:/Program Files/Microsoft VS Code/node_modules/typescript-tslint-plugin/index.js, c:/Program Files/Microsoft VS Code/node_modules/typescript-tslint-plugin/index.jsx, c:/Program Files/node_modules/typescript-tslint-plugin/package.json, c:/Program Files/node_modules/typescript-tslint-plugin.js, c:/Program Files/node_modules/typescript-tslint-plugin.jsx, c:/Program Files/node_modules/typescript-tslint-plugin/index.js, c:/Program Files/node_modules/typescript-tslint-plugin/index.jsx, c:/node_modules/typescript-tslint-plugin/package.json, c:/node_modules/typescript-tslint-plugin.js, c:/node_modules/typescript-tslint-plugin.jsx, c:/node_modules/typescript-tslint-plugin/index.js, c:/node_modules/typescript-tslint-plugin/index.jsx
`

**Comment by mjbvz** [comment]
Are you sure it's not loading? These errors are logged even when the plugin in loaded properly: https://github.com/Microsoft/TypeScript/issues/30106

Can you please provide the complete log

**Comment by pikadun** [comment]
@mjbvz 
[it is the log](https://gist.github.com/pikadun/62b0c81a37ad9b7053e0fbef0ae78723)

I installed 'typescript-tslint-plugin' in one of previous folders and it's the log,but it doesn't seem to work in vscode

**Comment by mjbvz** [comment]
The plugin is loading but this line suggests there may be something wrong with your tsconfig

```
Info 88   [11:28:55.501] [typescript-tslint-plugin] "[tslint] Tried to lint c:/Users/wg/Desktop/ts/greeter.ts but found no valid, enabled rules for this file type and file path in the resolved configuration."
```

Can you please share the tsconfig too

**Comment by pikadun** [comment]
@mjbvz thx! I didn't created the tsconfig file
