### ISSUE TITLE
Comment flags are ignored

### ISSUE THREAD

**Issue by GoGoris** [microsoft/vscode-typescript-tslint-plugin#91]
Ignoring rules using comment flags does not work.

Steps to reproduce:
1. Enable the rule triple-equals in tslint.json
2. Create a typescript file with the following contents: 
```
/* tslint:disable:triple-equals */
const doubleEquals = 0 == false;
```

Documentation: https://palantir.github.io/tslint/usage/rule-flags/

**Comment by mjbvz** [comment]
I can't repo this in version 1.2.0 of this extension with tslint 5.1.6

Are you sure the error you are seeing is from tslint? Your example produces a TS error as well

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint and this extension is no longer being maintained

Please look into migrating to use ESLint and the [ESLint VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
