### ISSUE TITLE
ProblemMatcher not working for TSLint >= 5.12

### ISSUE THREAD

**Issue by Springrbua** [microsoft/vscode-typescript-tslint-plugin#93]
Since version 5.12.0 the `prose` formatter uses `line:column` instead of `[line, column]`.
The `tslint5` ProblemMatcher is still using the old pattern and therefore, the problems won't be matched.
The new pattern should be something like this:
`^(WARNING|ERROR):(\\s+\\(\\S*\\))?\\s+(\\S.*):(\\d+):(\\d+)\\s+-\\s+(.*)$`

As a temporary workaround I overwrite the pattern in my task definition:
```
"problemMatcher": {
    "base": "$tslint5",
    "pattern": {
        "regexp": "^(WARNING|ERROR):(\\s+\\(\\S*\\))?\\s+(\\S.*):(\\d+):(\\d+)\\s+-\\s+(.*)$",
        "severity": 1,
        "file": 3,
        "line": 4,
        "column": 5,
        "message": 6
    }
}
```

**Comment by mjbvz** [comment]
Can you submit a PR that makes this change?

**Comment by Springrbua** [comment]
@mjbvz should a new matcher be added to stay compatible with tslint 5.11 and older?

**Comment by mjbvz** [comment]
Yes it probably should be a new one, unless you can write a regex that supports both outputs
